name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  unit:
    runs-on: ubuntu-latest
    outputs:
      tests: ${{ steps.scan.outputs.tests }}
    steps:
      - uses: actions/checkout@v4
      - id: scan
        run: echo "tests=$(find .github/tests -name '*.t' -type f | sort | xargs -n1 basename | jq -R -s -c 'split("\n") | map(select(length > 0))')" >> "$GITHUB_OUTPUT"

  tests:
    needs: unit
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test: ${{ fromJson(needs.unit.outputs.tests) }}
    name: "${{ matrix.test }}"
    steps:
      - uses: actions/checkout@v4
      - run: prove -v "$(find .github/tests -name '${{ matrix.test }}' -type f)"

  install:
    name: "Install"
    runs-on: ubuntu-latest
    container:
      image: ubuntu:24.04
      options: --privileged
    steps:
      - uses: actions/checkout@v4

      - name: Setup CSF
        uses: ./.github/actions/setup-csf

  smoke:
    name: "Smoke"
    needs: install
    runs-on: ubuntu-latest
    container:
      image: ubuntu:24.04
      options: --privileged
    steps:
      - uses: actions/checkout@v4

      - name: Setup CSF
        uses: ./.github/actions/setup-csf

      - name: Smoke CSF
        uses: ./.github/actions/smoke-csf

  uninstall:
    name: "Uninstall"
    needs: install
    runs-on: ubuntu-latest
    container:
      image: ubuntu:24.04
      options: --privileged
    steps:
      - uses: actions/checkout@v4

      - name: Setup CSF
        uses: ./.github/actions/setup-csf

      - name: Run uninstaller
        shell: bash
        run: |
          set -uo pipefail
          cd "$GITHUB_WORKSPACE"
          bash uninstall.sh

  compatibility:
    uses: ./.github/workflows/compatibility.yml
